num_ds_steps: 2
t_nhead: 4
t_emb_dim: 64
enable_local_window: True
initial_ds_size: 20
use_conv_proj: False
map_concat_mode: 'sum'
nb_convs: 10
enable_5x5_filter: True
weights: single_seq_rssm_weights.pkl